# Generated by Django 5.1.7 on 2025-03-14 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_link', models.CharField(max_length=1024, unique=True)),
                ('shorted_link', models.CharField(max_length=125, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_or_session_id', models.CharField(max_length=512)),
                ('link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit', to='link.link')),
            ],
        ),
    ]
